import {spawn} from 'node:child_process';
import {mkdir,readdir,stat,unlink,rename,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {encryptStream} from './backup-crypto.mjs';
const key=Buffer.from(process.env.BACKUP_ENCRYPTION_KEY||'','base64'),dir=process.env.BACKUP_DIR||'./backups';if(key.length!==32)throw new Error('Skonfiguruj BACKUP_ENCRYPTION_KEY.');
const retention=Number(process.env.BACKUP_RETENTION_DAYS||30),interval=Number(process.env.BACKUP_INTERVAL_SECONDS||86400);if(!Number.isInteger(retention)||retention<1||!Number.isInteger(interval)||interval<60)throw new Error('Niepoprawna retencja lub częstotliwość kopii.');
async function capture(command,args,target){const child=spawn(command,args,{stdio:['ignore','pipe','pipe']});const status=new Promise((resolve,reject)=>{child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(new Error('BACKUP_COMMAND_FAILED')));});child.stderr.resume();await Promise.all([encryptStream(child.stdout,target,key),status]);}
let running=false;
async function backup(){if(running)return;running=true;await mkdir(dir,{recursive:true,mode:0o700});const stamp=new Date().toISOString().replace(/[:.]/g,'-'),base=path.join(dir,`webify-${stamp}`);const files=[];try{await capture('pg_dump',['--format=custom','--no-owner','--no-acl','--dbname',process.env.BACKUP_DATABASE_URL||process.env.DATABASE_URL?.split('?')[0]||''],`${base}.db.tmp`);await rename(`${base}.db.tmp`,`${base}.db.enc`);files.push(path.basename(`${base}.db.enc`));if(process.env.STORAGE_DRIVER!=='s3'){await capture('tar',['-C',process.env.LOCAL_STORAGE_PATH||'./storage','-czf','-','.'],`${base}.files.tmp`);await rename(`${base}.files.tmp`,`${base}.files.enc`);files.push(path.basename(`${base}.files.enc`));}await writeFile(`${base}.json`,JSON.stringify({createdAt:new Date(),files,storage:process.env.STORAGE_DRIVER||'local',version:1}),{mode:0o600});await writeFile('/tmp/webify-backup-health',String(Date.now()));for(const f of await readdir(dir)){if(!/^webify-.*\.(enc|json|tmp)$/.test(f))continue;const target=path.join(dir,f);if((await stat(target)).mtimeMs<Date.now()-retention*86400000)await unlink(target);}console.log('Zapisano zaszyfrowaną kopię.');}catch{console.error('Kopia nie została ukończona. Sprawdź bazę, wolumeny i klucz.');if(process.argv.includes('--once'))process.exitCode=1;}finally{running=false;}}
await backup();if(!process.argv.includes('--once'))setInterval(()=>void backup(),interval*1000);
